name: "Nikurasu"                                # The name on the linktree
# profilePic:                                   # uncomment and set this if your profile pic has a custom name
theme: 'simple-orange'
links:
  - text: "YouTube"                             # text on the link
    hyperlink: "Test"                           # the actual hyperlink
    brandcolor: "youtube"                       # set this if you want to set the color of the link to the brand color of a platform...
    color: "#0D0D0D"                            # or that if you want to set it to an exact color
  - text: "Twitter"
    hyperlink: "test"
    brandcolor: "twitter"